### ISSUE TITLE
command-palette open chapters if 0 chapters then playlist won't open 

### ISSUE THREAD

**Issue by mrfragger** [stax76/mpv-scripts#15]
Applies to searching in command palette in playlist.  If you press up or down arrow with null or 1 character it will close and can't open command palette anymore until restarting mpv 0.36. 
`Extended-menu.lua:136 attempt to call field ‘unpack’ (a nil value)`

As long as there are 2 or more characters it works wonderfully.   I'm not sure if this is a extended-menu.lua issue I tried putting in command_palette.lua
`local menu_content = { filter_by_fields = {}, list = {}, current_i = nil, }`
but to no avail.  As it says in extended-menu.lua
```
  -- if value has 0 length, then search list item itself
  filter_by_fields = {},
```

maybe related to this code on Line #344 in extended-menu.lua
```
for _, v in ipairs(self.list.full) do
    -- if filter_by_fields has 0 length, then search list item itself
    if #self.filter_by_fields == 0 then
      if self:search_method(v) then table.insert(result, v) end
    else
```

**Comment by TheBestPessimist** [comment]
For me repro is even simpler than this: if there are no chapters, then command-palette is broken until mpv is restarted.

**Comment by stax76** [comment]
@mrfragger I could understand and fix what TheBestPessimist described, but your description I don't understand. Is it now solved?

**Comment by TheBestPessimist** [comment]
✅ Confirm my bug is fixed!

**Comment by stax76** [comment]
You're welcome!
