### ISSUE TITLE
Is it possible to make the script remove file to recycle bin only after i quit the file?

### ISSUE THREAD

**Issue by ayghub** [stax76/mpv-scripts#3]

**Comment by stax76** [comment]
It's not supported or planed. There is an alternative script you can try:

https://github.com/zenyd/mpv-scripts#delete-file

I believe there is another similar script, but I cannot find it now.

**Comment by jimmy-1000** [comment]
> ...

**stax76** Thanks a lot for your delete-current-file.lua 🙏
Your work give more powerful to mpv player 👌
