### ISSUE TITLE
Improvement related to delete-current-file

### ISSUE THREAD

**Issue by jimmy-1000** [stax76/mpv-scripts#5]
Hi, I have seen that when we delete a video in a folder with more videos, the file is deleted and mpv advances to the next one and plays it, this behavior is good. But if the video is the last one in the list and we delete it, mpv goes back to the previous video and plays it. Isn't it better that mpv is closed in this case?

**Comment by dyphire** [comment]
A simple patch to implement it, change `new_pos = pos - 1` to `new_pos = -1`.

**Comment by jimmy-1000** [comment]
> A simple patch to implement it, change `new_pos = pos - 1` to `new_pos = -1`.

It works !! Many thanks 👍
