### ISSUE TITLE
aur

### ISSUE THREAD

**Issue by BlurryFlurry** [stax76/mpv-scripts#6]
can we find this in aur repository?

**Comment by stax76** [comment]
Not from me.

**Comment by Estebiu** [comment]
> can we find this in aur repository?

Dude, just copy the file in your "~/.config/mpv/scripts" directory. It is not difficult.

**Comment by stax76** [comment]
The easiest way to download a file, btw. is:

1. Go to the file you want to download.
2. Click it to view the contents within the GitHub UI.
3. In the top right, click the `Raw` button.
4. Press `Ctrl+S`

Alternatively, it's possible to right-click the `Raw` button and choose 'Save link as'.

Unfortunately it's not obvious, I did it the wrong way myself far too often.
