### ISSUE TITLE
Delete and go to the next file while using uosc's built-in autoload

### ISSUE THREAD

**Issue by vitormathews** [stax76/mpv-scripts#8]
When using [uosc's autoload](https://github.com/tomasklaen/uosc/blob/main/script-opts/uosc.conf#L135) instead of the [classical one](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua) the player is closed after a file deletion, instead of playing the next file on the playlist.

Maybe this is because with uosc's autoload, the playlists are loaded in a different way, and the command ```script-message-to uosc next-file``` is neccessary instead of the default ```playlist-next```.

**Comment by stax76** [comment]
You can try and see if mpv behaves differently.

**Comment by stax76** [comment]
I don't understand what uosc autoload does and why it matters, you can try asking the uosc author about the problem.
